# Generated by Django 5.2.1 on 2025-06-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Título', max_length=200)),
                ('ano', models.IntegerField(help_text='Ano de lançamento')),
                ('genero', models.CharField(help_text='Gênero', max_length=100)),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
                'ordering': ['titulo'],
            },
        ),
    ]
